LCA Integration
NREL/GreenHEART pull request #56
Opened 2024-12-10 01:21 UTC by dakotaramos

LCA Integration
No new files added
Edited:
greenheart/tools/eco/utilities.py: added relevant imports, removed unnecessary lines of code for plots, created calculate_lca() function to run during post_process_simulation() pending greenheart_config yaml inputs
greenheart/simulation/greenheart_simulation.py: changed total_accessory_power_grid_kw to a np array and added argument inputs when calling post_process_simulation()
greenheart/tools/eco/finance.py: updated summation of total_accessory_power_grid_kw given it is now a np array
examples/02-... and 03-... py files: to run post_processing and run LCA 
[examples/inputs/plant/greenheart_config_<X>.yamls: added lca_config section to input yamls to run calculate_lca() in examples

## Related issue
https://github.com/NREL/GreenHEART/issues/12
https://github.com/NREL/HOPP/pull/380
https://github.com/NREL/HOPP/pull/408

## Impacted areas of the software
utilities.py and examples

## Additional supporting information
This work is being completed for the LCA integration, the data pulling and parsing will live in HOPP. 

NOTE: 

- This is a Level 0 integration of the project code Masha and Evan originally created for Green Steel, with expectations to continue to develop this framework as we build out the modularity of GreenHEART
- No pytests for this functionality were create yet, this is dependent on merging of https://github.com/NREL/HOPP/pull/408 into HOPP/main so GreenHEART can pull the appropriate GREET data

## Test results, if applicable
NA (see note above).

2024-12-10 17:32 UTC, dakotaramos commented
Note, I put all lca configuration in the input yamls under a section lca_config: in the greenheart_config input yamls. I acknowledge that some of these could warrant their own section (cambium, feedstocks) or in existing sections (electrolyzer type under electrolyzer) but opted to keep them separate for now with the thought being these will be adjusted with the modularization refactor of greenheart.

2024-12-10 18:52 UTC, dakotaramos commented
I see checks failed, I believe this is because it is installing HOPP 3.0 and the cambium_data.py was added into HOPP 3.1

2024-12-11 16:23 UTC, jmartin4nrel reviewed
My biggest comment is, holy crap, a 2700-line file... why didn't we split this into separate files? When we make new greenheart let's think about how this can better be organized into separate functions and files with an import hierarchy so we're not scrolling for days. I bet there's also ways to give things dynamic naming and looping through them, like an "EI_dict" that has levels, e.g. "EI_dict['capex']['nuclear']['BWR'] instead of having to tediously name everything individually and manually, like 'nuclear_BWR_capex_EI'. Just ideas, there may be good reasons for this I don't understand because I didn't develop it! I say we go ahead and merge to get the LCA functionality a-rolling!

2024-12-11 17:15 UTC, dakotaramos commented
@jmartin4nrel I 100% agree, a 2700 line file is massive. For clarity the original direction I was given was to integrate [ Masha and Evan's project code / script ](https://github.nrel.gov/JThomas2/GreenSteel/blob/main/src/ereznic2/LCA_green_steel_ammonia_ProFAST.py) such that it could run in HOPP/GreenHEART as it was / is, while concurrently adding SMR and ATR functionality.

That said I am open to any / all suggestions, thoughts, feedback on how to make this code more functional, efficient, etc. So please everyone who sees this, use this as a forum to capture those thoughts and ideas with the intention that this LCA integration will morph as we continue to develop HOPP and GreenHEART.

I like the idea of dynamic naming and an EI_dict. I believe there are multiple opportunities to make this script more dynamic such that based on the actual system modeled / configuration we dynamically only load specific variables and only perform specific computations based off that configuration.

2024-12-11 17:59 UTC, dakotaramos commented
@elenya-grant added you as a reviewer just in case, specifically hoping to get a second set of eyes on the small changes I made in greenheart_simulation.py for the total_accessory_power_grid_kw. I had turn this into an array instead of a float since we're using hourly timeseries in the lca calculations (similar to total_accessory_power_renewable_kw).

2024-12-12 18:53 UTC, kbrunik commented on examples/01-green-hydrogen.ipynb
For the Jupyters could you add a little bit of text  in markdown the "Create Full Configuration to Run GreenHEART Simulation" section about how the LCA is turned on when you set `post_process=True` in `GreenHeartSimulationConfig()`? And in the "Run the GreenHEART Simulation" about the post-process outputs and where to find them?

2024-12-12 18:53 UTC, kbrunik commented on examples/01-green-hydrogen.ipynb
It looks like you didn't run the last cell of the Jupyter notebooks, would you be able to push a version where you run it so it shows the outputs?

2024-12-12 18:53 UTC, kbrunik commented on greenheart/tools/eco/utilities.py
> +    # return 0
Let's delete the commented out return

2024-12-12 18:53 UTC, kbrunik commented on greenheart/tools/eco/utilities.py
> +    # Instantiate object to hold EI values per year
Thoughts about doing something like this?
```
# Define technologies, processes, and intensity types
technologies = ["electrolysis", "smr", "smr_ccs", "atr", "atr_ccs", "NH3_electrolysis", "NH3_smr", "NH3_smr_ccs", "NH3_atr", "NH3_atr_ccs", "steel_electrolysis", "steel_smr", "steel_smr_ccs", "steel_atr", "steel_atr_ccs"]
intensity_types = ["Scope3", "Scope2", "Scope1", "total"]

# Initialize lists and corresponding values
emission_data = {
    f"{tech}_{intensity}_emission_intensity": []
    for tech in technologies
    for intensity in intensity_types
}

emission_values = {
    f"{tech}_{intensity}_EI": globals().get(f"{tech}_{intensity}_EI", np.nan)
    for tech in technologies
    for intensity in intensity_types
}

# Append values dynamically
for key in emission_data:
    emission_data[key].append(emission_values[key])
```

2024-12-12 18:53 UTC, kbrunik commented on greenheart/tools/eco/utilities.py
> +    # Instantiate lists to hold interpolated data
Perhaps similarly (could reuse the previous `technologies` and `intensity_types`)
```
# Define technologies, processes, and intensity types
technologies = ["electrolysis", "smr", "smr_ccs", "atr", "atr_ccs", "NH3_electrolysis", "NH3_smr", "NH3_smr_ccs", "NH3_atr", "NH3_atr_ccs", "steel_electrolysis", "steel_smr", "steel_smr_ccs", "steel_atr", "steel_atr_ccs"]
intensity_types = ["Scope3", "Scope2", "Scope1", "total"]

# Initialize lists and corresponding values
interpolated_data = {
    f"{tech}_{intensity}_interpolated": []
    for tech in technologies
    for intensity in intensity_types
}
```

2024-12-12 18:53 UTC, kbrunik commented on greenheart/tools/eco/utilities.py
> +    electrolysis_emission_intensity = []
I think I'd like it better if we call it `emission_total` rather than just `emission` to follow the same format above

2024-12-12 18:53 UTC, kbrunik commented on greenheart/tools/eco/utilities.py
> +    # Instantiate dataframe from dictionary of emission intensity lists
Is there a reason to translate the emission intensity outputs into a DataFrame? Is it necessary for subsequent calculations?

2024-12-12 18:53 UTC, kbrunik commented on greenheart/tools/eco/utilities.py
> +            electrolysis_Scope3_EI_interpolated.append(emission_intensities_df['electrolysis Scope3 EI (kg CO2e/kg H2)'].values[0][0])
Like here, wouldn't be simpler if we keep using the np array you had already output?

2024-12-12 18:53 UTC, kbrunik commented on greenheart/tools/eco/utilities.py
> +    # Loop through years between cambium_year and endoflife_year, interpolate values
I think we could do more dynamic looping through technologies in the if statements here as well since there are lot of calculations that are being repeated for each variable

2024-12-12 18:53 UTC, kbrunik commented on greenheart/tools/eco/utilities.py
> +def calculate_lca(
Would love a high-level docstring of what happens in this function if possible

2024-12-17 20:59 UTC, RHammond2 commented
@dakotaramos it looks like there is an issue finding the `cambium_data` module, I believe the HOPP dependency should be bumped to `"hopp>=3.1"` to resolve this.

error line: https://github.com/NREL/GreenHEART/actions/runs/12262565196/job/34559066137?pr=56#step:8:30

2024-12-19 16:06 UTC, dakotaramos commented
> I see checks failed, I believe this is because it is installing HOPP 3.0 and the cambium_data.py, greet_data.py, and greet_2023_processed.yaml was added into HOPP 3.1

@RHammond2 That is correct, I flagged that in the comments earlier in the thread but we were waiting for the cambium and greet data (HOPP v3.1) to be available through pypi. Furthermore, this integration actually needs to pull HOPP V3.1.1 with the GREET Hotfix in their (additional items in the greet_2023_processed.yaml used in this code).

2024-12-19 16:07 UTC, dakotaramos commented
As a note, I see feedback and will work on this next week. I have immediate deliverables this week on another projects that take priority at the moment.

2024-12-24 19:26 UTC, mariya-koleva approved these changes
In terms of LCA methodology, the utilities.py script looks good (haven't tested it though). I am aware you made some tests for comparison between GREET and the script so, please, make sure you have a folder with those saved somewhere, for reference.

2025-01-15 16:23 UTC, jaredthomas68 requested changes
I am generally on board with this PR. I agree with @kbrunik and @jmartin4nrel  that a lot of this should be written in a less manual way. It is very easy for bugs to creep in unnoticed in the way this is currently written. If there is a possibility of shifting the parts noted by @kbrunik I think it would be a significant improvement and would set us on a better trajectory. My thought is that it will be much easier to do that now when you have the GREET details fresh in your mind. Eventually some of this may move to be handled by individual technologies.

2025-01-15 16:23 UTC, jaredthomas68 commented on greenheart/simulation/greenheart_simulation.py
> +            # total_accessory_power_grid_kw = 0.0
I think we can just remove this line rather than comment it out

2025-01-15 16:23 UTC, jaredthomas68 commented on greenheart/tools/eco/utilities.py
> -    if ax == None:
I see the removal of the ax check. I was going to add some plotting here, but did not. Let's remove the `ax=None` optional input as well.

2025-01-15 16:23 UTC, jaredthomas68 commented on greenheart/tools/eco/utilities.py
> +def calculate_lca(
ditto

2025-01-15 16:23 UTC, jaredthomas68 commented on greenheart/tools/eco/utilities.py
> +    if len(renewable_technologies_modeled) > 1:
We may be adding non-renewables to hopp and/or greenheart at some point, which would make this check incorrect. I'm not sure the best way to plan for that, and I think we can just let it go for now, but I would like it noted here and on the radar.

2025-01-15 16:23 UTC, jaredthomas68 commented on greenheart/tools/eco/utilities.py
> +        annual_energy_to_electrolyzer_from_grid = energy_to_electrolyzer + energy_to_peripherals                        # Average Annual electricity to electrolyzer and peripherals from grid power wh
Should the energy_to_peripherals be included here?

2025-01-15 18:14 UTC, dakotaramos commented on greenheart/tools/eco/utilities.py
> +        annual_energy_to_electrolyzer_from_grid = energy_to_electrolyzer + energy_to_peripherals                        # Average Annual electricity to electrolyzer and peripherals from grid power wh
@jaredthomas68 this was the logic that we landed on in our meeting on 11/14. From my notes: when it is a grid-only case, ideally we have a new output but for this iteration use energy_to_electrolyzer + energy to peripherals output from simple solver

If you think this should be different let me know, but this is intended to capture total grid power used by electrolyzer and electrolyzer balance of plant / peripherals so we can calculate associated emissions of that power use.

2025-01-15 19:12 UTC, dakotaramos commented on greenheart/tools/eco/utilities.py
> +    if len(renewable_technologies_modeled) > 1:
@jaredthomas68 I 100% agree this is not the most ideal solution. I'm open to other ideas here but this was what we landed on after talking with Kaitlin and Elenya (I think) about how to best identify what technologies are being modeled in the current system / run. I also spoke with @johnjasa about this in discussions about new modular ODIES, so it is on his radar that I'm looking for a better solution in the new modular framework which I think it will be easier to identify between different technologies. I also thought about having it check against a set of hardcoded technologies that are being modeled / maintained in HOPP (wind, pv, etc), but leaned against more hardcoded values here.

2025-01-15 19:14 UTC, dakotaramos commented on greenheart/tools/eco/utilities.py
> -    if ax == None:
@jaredthomas68 understood, yea I took this out as part of troubleshooting of empty plots being displayed in the reference design .ipynb outputs even when show_plots = False.

To confirm you agree with removing these lines but also want to take out the input argument ax=None? I'll double check that isn't used anywhere else in the function before doing so, but can do that.

2025-01-15 19:14 UTC, dakotaramos commented on greenheart/simulation/greenheart_simulation.py
> +            # total_accessory_power_grid_kw = 0.0
Copy that will do.

2025-01-15 22:23 UTC, dakotaramos commented on examples/01-green-hydrogen.ipynb
@kbrunik the post_process_simulation() function (which is run when post_processing=True) does quite a few things like print additional stuff to terminal, visualize the plant and show or save those plots, saves profast cost breakdowns, saves annual_energy_breakdown, saves orbit cost information, and saves hourly_energy_breakdown. I don't know if I know enough about some of those processes to really describe them. I took a stab at detailing some of the ones I have knowledge on.

Thoughts?

![image](https://github.com/user-attachments/assets/17129904-2f06-4663-bf5a-f1aa45910f0f)

2025-01-15 23:15 UTC, dakotaramos commented on greenheart/tools/eco/utilities.py
> +def calculate_lca(
@kbrunik @jaredthomas68 how does this look? I was going to add verbiage about the current status of the LCA calculations and how it is heavily oriented toward H2, NH3, and Steel production right now but opted not to. Thoughts?

![image](https://github.com/user-attachments/assets/d441242c-5dc6-499a-9e50-0e9b9806b55f)

2025-01-15 23:20 UTC, dakotaramos commented on greenheart/tools/eco/utilities.py
> +    # return 0
Corrected

2025-01-16 20:10 UTC, dakotaramos commented on greenheart/tools/eco/utilities.py
> +    # Instantiate object to hold EI values per year
@kbrunik I like this, and I've updated the code accordingly. Question: in the emission_values dictionary why use globals().get(...., np.nan)? From what I found online the globals().get() functionality checks the global variables within the function and returns the default (np.nan) if it is not found. Is there a reason for doing this rather than just f"{tech}_{intensity}_EI": np.nan?

Also just a side note, for appending the values dynamically, I also like this but with the difference in keys (_EI vs _emissions_intensity) this returns an error, so I'll have to update the keys to be the same or do some string manipulation to map X_EI to X_emission_intensity

2025-01-17 18:13 UTC, jaredthomas68 commented on greenheart/tools/eco/utilities.py
> +        annual_energy_to_electrolyzer_from_grid = energy_to_electrolyzer + energy_to_peripherals                        # Average Annual electricity to electrolyzer and peripherals from grid power wh
Ok, I think perhaps the name `annual_energy_to_electrolyzer_from_grid` is what threw me off. Maybe we should change that to `annual_energy_for_electrolyzer_and_peripherals_from_grid`, just to be transparent

2025-01-17 18:20 UTC, jaredthomas68 commented on greenheart/tools/eco/utilities.py
> +def calculate_lca(
the "Assessment" and "analysis" are redundant. Also, can you clarify what the little "e" means for readers? Otherwise this looks fine.

2025-01-17 18:25 UTC, jaredthomas68 commented
> In terms of LCA methodology, the utilities.py script looks good (haven't tested it though). I am aware you made some tests for comparison between GREET and the script so, please, make sure you have a folder with those saved somewhere, for reference.

@dakotaramos would it work to add these tests to the test suite? We really should have some formal tests around this functionality.

2025-01-17 19:40 UTC, dakotaramos commented on greenheart/tools/eco/utilities.py
> +def calculate_lca(
Copy that, removed "analysis" and added another line explain what CO2e is
![image](https://github.com/user-attachments/assets/98970662-824d-46f5-8045-29ffc37995ea)

2025-01-17 19:48 UTC, dakotaramos commented on greenheart/tools/eco/utilities.py
> +        annual_energy_to_electrolyzer_from_grid = energy_to_electrolyzer + energy_to_peripherals                        # Average Annual electricity to electrolyzer and peripherals from grid power wh
Copy that, updated.

2025-01-21 20:22 UTC, dakotaramos commented on greenheart/tools/eco/utilities.py
> +    # Loop through years between cambium_year and endoflife_year, interpolate values
Corrected with dynamic looping

2025-01-21 20:33 UTC, dakotaramos commented on examples/01-green-hydrogen.ipynb
Corrected

2025-01-21 20:33 UTC, dakotaramos commented on greenheart/tools/eco/utilities.py
> +    # Instantiate lists to hold interpolated data
Updated

2025-01-21 20:33 UTC, dakotaramos commented on greenheart/tools/eco/utilities.py
> +    electrolysis_emission_intensity = []
updated

2025-01-21 20:34 UTC, dakotaramos commented on greenheart/tools/eco/utilities.py
> +    # Instantiate dataframe from dictionary of emission intensity lists
This was how it was previously done, but you are correct, its easier to use the np arrays, updated accordingly

2025-01-21 20:34 UTC, dakotaramos commented on greenheart/tools/eco/utilities.py
> +            electrolysis_Scope3_EI_interpolated.append(emission_intensities_df['electrolysis Scope3 EI (kg CO2e/kg H2)'].values[0][0])
updated

2025-01-24 21:45 UTC, dakotaramos reviewed
"reviewed" Jared requested changes

2025-01-27 16:27 UTC, merged